name: Initialize
on:
  workflow_call:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: false
          cache: gradle

      - name: Java Version
        run: javac -version

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

