name: Ketch Github Actions For PR
on:
  pull_request:
    branches: [ "master","dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    needs:
      - Initialize
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/workflows/Initialize.yml

      - name: Build The Project
        run: ./gradlew clean build

  test:
    runs-on: ubuntu-latest
    needs:
      - Initialize
      - build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: ./.github/workflows/Initialize.yml
      - name: Run Test
        run: ./gradlew testDebugUnitTest --continue
      - name: Upload Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: '**/build/reports/tests/'